spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: xkc
    password: szyxwd
    driver-class-name: com.mysql.cj.jdbc.Driver

